### ISSUE TITLE
Problem of building of a test using Geant10.9.6ref10 IB

### ISSUE THREAD

**Issue by civanch** [cms-sw/cmsdist#265] opened 2013-11-08 14:32 UTC
When update any package and trying to build locally a test therê is a problem whihc is seen like:

```
/afs/cern.ch/cms/sw/ReleaseCandidates/vol1/slc5_amd64_gcc481/external/gcc/4.8.1/bin/../lib/gcc/x86_64-redhat-linux-gnu/4.8.1/../../../../x86_64-redhat-linux-gnu/bin/ld: 
_ZN14G4GeomSplitterI8G4LVDataE6offsetE: TLS reference in /afs/cern.ch/cms/sw/ReleaseCandidates/vol1/slc5_amd64_gcc481/cms/cmssw/CMSSW_7_0_GEANT10_X_2013-11-06-1400/external/slc5_amd64_gcc481/lib/libG4digits_hits.so
mismatches non-TLS reference in
tmp/slc5_amd64_gcc481/src/Alignment/LaserAlignmentSimulation/src/AlignmentLaserAlignmentSimulation/LaserSteppingAction.o
```

The problem is connected with the fact that geant4 9.6ref10 was build with the flag -DGEANT4_BUILD_MULTITHREADED=ON while simple "scram b -j8" does not know anything about MULTITHREADED. How to tell scram about this flag?

**Comment by davidlt** [comment] 2013-11-08 14:36
@civanch do you mean that a special macro needs to be defined during compilation? `GEANT4_BUILD_MULTITHREADED` is CMake variable for compiling GEANT4.

**Comment by civanch** [comment] 2013-11-08 14:39
Yes, exactly. It is not enough to set corresponding environment variable, some compiler flag or option is needed.

**Comment by davidlt** [comment] 2013-11-08 14:47
@civanch provide me such options and I will add them to GEANT4 toolfile, thus SCRAM always will add them for GEANT4 related parts.

**Comment by civanch** [comment] 2013-11-08 14:51
I will check promptly.

**Comment by civanch** [comment] 2013-11-13 07:41
What I see in Geant4 makefiles is only an addition to compillation flags: CPPFLAGS += -DG4MULTITHREADED, nothing more seems to be needed.

**Comment by davidlt** [comment] 2013-11-13 08:04
Done. Add to `geant4core` toolfile, please report back after 1400 IB. If there will be no issues the ticket will be closed.

BTW, do we realy want to have multi-threaded GEANT4 in CMSSW? So far GEANT4 is used in a single threaded way AFAIK.

**Comment by civanch** [comment] 2013-11-13 08:23
It the goal to build against Geant4 MT independently if SIM will be used MT or sequential - this will be easier to maintain

**Comment by civanch** [comment] 2013-11-13 18:30
Unfortunately, does not work. How I check:

cmsrel CMSSW_7_0_GEANT10_X_2013-11-13-1400
cd CMSSW_7_0_GEANT10_X_2013-11-13-1400/src
cmsenv
git cms-addpkg SimG4Core/Application
scram b -j8

Application is compiled normally but plugin is not created:

Caught exception An exception of category 'PluginLibraryLoadError' occurred.
Exception Message:
unable to load lib/slc5_amd64_gcc481/pluginSimG4CoreApplicationPlugins.so because /afs/cern.ch/cms/sw/ReleaseCandidates/vol0/slc5_amd64_gcc481/cms/cmssw/CMSSW_7_0_GEANT10_X_2013-11-13-1400/external/slc5_amd64_gcc481/lib/libG4particles.so: cannot allocate memory in static TLS block
 will ignore pluginSimG4CoreApplicationPlugins.so and continue.

> > Pluging of all type refreshed.

**Comment by davidlt** [comment] 2013-11-13 19:11
@civanch for this particular error you would need to investigate gcc, binutils, and glibc. The error comes from glibc once dlopen() is invoked, I assume:

```
 38 /* We are trying to perform a static TLS relocation in MAP, but it was
 39    dynamically loaded.  This can only work if there is enough surplus in
 40    the static TLS area already allocated for each running thread.  If this
 41    object's TLS segment is too big to fit, we fail.  If it fits,
 42    we set MAP->l_tls_offset and return.
 43    This function intentionally does not return any value but signals error
 44    directly, as static TLS should be rare and code handling it should
 45    not be inlined as much as possible.  */
 46 int
 47 internal_function
 48 _dl_try_allocate_static_tls (struct link_map *map)
 49 {
 50   /* If we've already used the variable with dynamic access, or if the
 51      alignment requirements are too high, fail.  */
 52   if (map->l_tls_offset == FORCED_DYNAMIC_TLS_OFFSET
 53       || map->l_tls_align > GL(dl_tls_static_align))
 54     {
 55     fail:
 56       return -1;
 57     }

<snip>

113 void
114 internal_function __attribute_noinline__
115 _dl_allocate_static_tls (struct link_map *map)
116 {
117   if (map->l_tls_offset == FORCED_DYNAMIC_TLS_OFFSET
118       || _dl_try_allocate_static_tls (map))
119     {
120       _dl_signal_error (0, map->l_name, NULL, N_("\
121 cannot allocate memory in static TLS block"));
122     }
123 }
```

There are/were some bugs related to TLS in many places, incl. glibc, e.g: https://sourceware.org/bugzilla/show_bug.cgi?id=14898

My initial answer would be: debug glibc.

**Comment by civanch** [comment] 2013-11-14 12:12
It turns out that extra compilation flags are needed:  CXXFLAGS += -ftls-model=initial-exec -pthread

**Comment by davidlt** [comment] 2013-11-14 12:26
Just adding it [`-ftls-model=initial-exec -pthread`] for a single package will not help. I just tested that. If you prefer we can recompile the whole CMSSW with these two flags for testing locally.

```
export USER_CXXFLAGS='-ftls-model=initial-exec -pthread'

<snip>

unable to load lib/slc5_amd64_gcc481/pluginSimG4CoreApplicationPlugins.so because /afs/cern.ch/cms/sw/ReleaseCandidates/vol0/slc5_amd64_gcc481/cms/cmssw/CMSSW_7_0_GEANT10_X_2013-11-13-1400/external/slc5_amd64_gcc481/lib/libG4particles.so: cannot allocate memory in static TLS block
```

**Comment by civanch** [comment] 2013-11-14 13:10
Yes, these flags are needed for compillation of all packages which depends on geant4. May be easier to use these flags for all CMSSW.

**Comment by davidlt** [comment] 2013-11-14 17:13
Attempting to launch a test build with these flags for CMSSW (does not incl. externals). Available on `vocms18`.

```
export SCRAM_ARCH=slc5_amd64_gcc481
. /build/davidlt/geant4full/a/cmsset_default.sh
scram p CMSSW_7_0_GEANT10_X_2013-11-14-0200
```

Full CMSSW with `-ftls-model=initial-exec -pthread`, no change.

**Comment by civanch** [comment] 2013-11-20 13:56
I had a look once more and observe that there is no complain to a sub-package library but only to plugin sub-library of the sub-package. May it be that this USER_CXXFLAGS  is used to build src but not used to build plugin?

**Comment by davidlt** [comment] 2013-11-20 14:01
No, I added the options to `gcc-toolfile` in the CMSSW test build (previous message). Thus it should be added to every C++ compiled object (in CMSSW only).

**Comment by civanch** [comment] 2013-11-20 19:39
Hi David,

I have tried apply CXXFLAGS locally trying to recompile few packages

scram b USER_CXXFLAGS="-ftls-model=initial-exec -pthread"

but fail: scram not allow me and at the same time indicate that

USER_CXXFLAGS = -ftls-model=initial-exec

without  '-pthread', can this be a problem?

Cheers,
Vladimir

**Comment by davidlt** [comment] 2013-11-20 19:49
Please, provide exact command and exact output. My current advice export `USER_CXXFLAGS` before launching scram command as on my previous example on the thread.

**Comment by civanch** [comment] 2013-11-20 19:50
full list of Geant4 compile options is at

http://cern.ch/vnivanch/Linux-g++.gmk

may be there is some other difference.

Cheers,
Vladimir

**Comment by civanch** [comment] 2013-11-20 20:52
Unfortunately, rebuild with environemnt variable defined does not work. 
Cheers,
Vladimir

**Comment by civanch** [comment] 2013-11-21 09:34
I have discussed scram compile and link  commands in verbose mode with Geant4 experts and it seems that they are OK. The only idea: may be edmWriteConfig when is built or is executed needs same or similar options. The bug happens when plugin library is loaded:

@@@@ Running edmWriteConfigs for SimG4CoreCustomPhysicsPlugins
error: edmWriteConfigs caught an exception while loading a plugin library.

**Comment by smuzaffar** [comment] 2013-11-21 09:44
it these flags are needed for the packages/plugins which uses geant4 then please add these flags in gean4core.xml file i.e. in geant4-toolfile.

**Comment by davidlt** [comment] 2013-11-21 09:47
And it is in a test build.

```
>> Compiling  /build/davidlt/geant4full/a/tmp/BUILDROOT/52c6717aa7e02c25172b0d3ee360a057/opt/cmssw/slc5_amd64_gcc481/cms/cmssw/CMSSW_7_0_GEANT10_X_2013-11-14-0200/src/FWCore/ParameterSet/bin/edmWriteConfigs.cpp
/build/davidlt/geant4full/a/slc5_amd64_gcc481/external/gcc/4.8.1/bin/c++ -c -DGNU_GCC -D_GNU_SOURCE -DPROJECT_NAME="CMSSW" -DPROJECT_VERSION="CMSSW_7_0_GEANT10_X_2013-11-14-0200" -I/build/davidlt/geant4full/a/tmp/BUILDROOT/52c6717aa7e02c25172b0d3ee360a057/opt/cmssw/slc5_amd64_gcc481/cms/cmssw/CMSSW_7_0_GEANT10_X_2013-11-14-0200/src -I/build/davidlt/geant4full/a/slc5_amd64_gcc481/lcg/root/5.34.10/cint -I/build/davidlt/geant4full/a/slc5_amd64_gcc481/external/boost/1.51.0-cms/include -I/build/davidlt/geant4full/a/slc5_amd64_gcc481/external/libuuid/2.22.2/include -I/build/davidlt/geant4full/a/slc5_amd64_gcc481/external/pcre/7.9__8.33/include -I/build/davidlt/geant4full/a/slc5_amd64_gcc481/external/bz2lib/1.0.5/include -I/build/davidlt/geant4full/a/slc5_amd64_gcc481/external/tbb/42_20130725oss/include -I/build/davidlt/geant4full/a/slc5_amd64_gcc481/external/zlib/1.2.8/include -I/build/davidlt/geant4full/a/slc5_amd64_gcc481/lcg/root/5.34.10/include -O2 -pthread -pipe -Werror=main -Werror=pointer-arith -Werror=overlength-strings -Wno-vla -Werror=overflow -Wstrict-overflow -std=c++11 -msse3 -ftree-vectorize -Wno-strict-overflow -Werror=array-bounds -Werror=format-contains-nul -Werror=type-limits -fvisibility-inlines-hidden -fno-math-errno --param vect-max-version-for-alias-checks=50 -fipa-pta -felide-constructors -fmessage-length=0 -ftemplate-depth-300 -Wall -Wno-non-template-friend -Wno-long-long -Wreturn-type -Wunused -Wparentheses -Wno-deprecated -Werror=return-type -Werror=missing-braces -Werror=unused-value -Werror=address -Werror=format -Werror=sign-compare -Werror=write-strings -Werror=delete-non-virtual-dtor -Werror=maybe-uninitialized -Werror=strict-aliasing -Werror=narrowing -Werror=uninitialized -Werror=unused-but-set-variable -Werror=reorder -Werror=unused-variable -Werror=conversion-null -Werror=switch -fdiagnostics-show-option -Wno-unused-local-typedefs -Wabi -ftls-model=initial-exec -pthread -DBOOST_DISABLE_ASSERTS -fPIC -MMD -MF tmp/slc5_amd64_gcc481/src/FWCore/ParameterSet/bin/edmWriteConfigs/edmWriteConfigs.d /build/davidlt/geant4full/a/tmp/BUILDROOT/52c6717aa7e02c25172b0d3ee360a057/opt/cmssw/slc5_amd64_gcc481/cms/cmssw/CMSSW_7_0_GEANT10_X_2013-11-14-0200/src/FWCore/ParameterSet/bin/edmWriteConfigs.cpp -o tmp/slc5_amd64_gcc481/src/FWCore/ParameterSet/bin/edmWriteConfigs/edmWriteConfigs.o
```

```
...  -Wabi -ftls-model=initial-exec -pthread -DBOOST_DISABLE_ASSERTS ...
```

Again, in the test build I added the flags for all C++ compilations inside CMSSW.

You can test locally by recompiling `FWCore/ParameterSet`.

**Comment by davidlt** [comment] 2013-11-21 09:48
@smuzaffar they are already added. Again, my suggestion is to debug glibc to figure out why it rejects the DSO with TLS.

**Comment by davidlt** [comment] 2013-11-21 10:16
Currently what I see is that `libG4particles.so` contains 0x0000000000000510 (1296) bytes of TLS. TLS should take space from thread stack size. Basically `stack_size = initial_stack_size - <sum_of_all_TLS_from_all_DSOs>`. Found another bug report for _glibc 2.12_ (I think, that's SLC6), that it does not handle big TLS segments.

From current _glibc trunk_:

```
...This can only work if there is enough surplus in
 40    the static TLS area already allocated for each running thread.  If this
 41    object's TLS segment is too big to fit, we fail.
```

This is what you would need to check, what is the overall TLS size and is there enough space to store it.

**Comment by davidlt** [comment] 2013-11-21 10:57
I decided to look into dynamic loader debug output, 121 libs existing for edmWriteConfigs call. Checking each of them and summing TLS blocks:

```
0x0000000000000038 56
0x0000000000000078 120
0x0000000000000020 32
0x0000000000000060 96
0x0000000000000028 40
0x0000000000000008 8
0x0000000000000028 40
0x0000000000000008 8
0x0000000000000038 56
0x0000000000000058 88
0x0000000000000030 48
0x0000000000000218 536
0x0000000000000108 264
0x00000000000000b8 184
0x0000000000000020 32
0x0000000000000018 24
0x0000000000000510 1296
0x0000000000000088 136
0x00000000000001f2 498
0x00000000002ed220 3068448
0x0000000000000008 8
0x0000000000000068 104
0x0000000000000048 72
0x0000000000000038 56
0x0000000000000018 24
Total: 3072274
```

_Possibly_ 3000.26 KBs for TLS.

The behemoth is `libG4processes.so`, my short experience with TLS things and I never saw such big TLS segment.

```
/afs/cern.ch/cms/sw/ReleaseCandidates/vol1/slc5_amd64_gcc481/cms/cmssw/CMSSW_7_0_GEANT10_X_2013-11-21-0200/external/slc5_amd64_gcc481/lib/libG4processes.so
 TLS            0x0000000000f22a58 0x0000000000f23a58 0x0000000000f23a58
                0x00000000001844e8 0x00000000002ed220  R      8
```

Usually TLS blocks are small, i.e., some bites, but not megabytes.

Still you would need to debug gblic to get the answer.

**Comment by civanch** [comment] 2013-11-21 12:01
IN G4 we always have process library about 10 time larger than the geometry library, other libraries are smaller. This huge amount of TLS will be discussed within Geant4 to see if it can be reduced.

However, I have observed the same problem when link CMSSW sub-package which does not use G4 physics. May it be that TSL size limit can be increased by some option ( to increase GL(dl_tls_static_align) ) ?

**Comment by davidlt** [comment] 2013-11-21 13:21
If you have observed it with not G4 10, please, provide a reproducer.

Regarding TLS the bug report is here: https://sourceware.org/bugzilla/show_bug.cgi?id=11787

More: https://sourceware.org/glibc/wiki/Release/2.18

I tested on SLC5 with glibc 2.5 and it did not pass the testcase. My current guess is that it does not fit into TLS storage, debugging glibc might confirm it.

If the problem is glibc, we cannot replace/patch it.

**Comment by civanch** [comment] 2013-11-21 21:39
Hi David your analysis allowed to find a terrible class inside Geant4. 
A new candidate version of Geant4 has been prepared which includes fixes allowing to reduce TLS size:

http://cern.ch/vnivanch/geant4.10.0cand00a.tar.gz

this version is more closed to the final one. Would it be possible to substitute the previous and try to rebuild CMSSW from scratch?

**Comment by davidlt** [comment] 2013-11-21 22:09
I am updating it for 0200 IB.

After looking into `libG4processes.so`, it now went from 0x00000000002ed220 to 0x00000000000662c0 for TLS. Which is from 2996.53125 kilobytes to 408.6875 kilobytes. I still would say that TLS segment is big, but it's a very nice improvement. We'll see if there is any effect in 0200 IB.

**Comment by civanch** [comment] 2013-11-22 17:30
Geant4 experts suggest to try to switch to slc6_amd64_gcc481

**Comment by civanch** [comment] 2013-11-22 17:48
I have tried to re-build and clearly see not only libG4processes.so problem by libG4particles.so as well.

Exception Message:
unable to load lib/slc5_amd64_gcc481/pluginValidationGeometry.so because /afs/cern.ch/cms/sw/ReleaseCandidates/vol1/slc5_amd64_gcc481/cms/cmssw/CMSSW_7_0_GEANT10_X_2013-11-22-1400/external/slc5_amd64_gcc481/lib/libG4particles.so: cannot allocate memory in static TLS block
 will ignore pluginValidationGeometry.so and continue.
Caught exception An exception of category 'PluginLibraryLoadError' occurred.

**Comment by davidlt** [comment] 2013-11-22 19:46
I found it not so trivial to debug ld-linux with SLC5 and CMSSW environment. I looked into glibc 2.5 code.

The TLS size is:

```
206   GL(dl_tls_static_size) = (roundup (offset + TLS_STATIC_SURPLUS, max_align)
207           + TLS_TCB_SIZE);
```

Where `TLS_STATIC_SURPLUS` is

```
# define TLS_STATIC_SURPLUS        64 + DL_NNS * 100
```

Here `DL_NNS` is most likely 16.

Thus `TLS_STATIC_SURPLUS` is **1664** (bytes?). Actually there are additional things, which increase TLS size is you can see from the formula.

I was playing with that glibc test case it failed the last working TLS stored variable was: `__thread int x[1688];` which brings TLS size to **10240** for this particular test case. This information was received by using `_dl_get_tls_static_info`. I found that in GCC for Go language in order not to fail while creating a thread, they query TLS size information from dynamic linker and modify stack size by adding TLS size. It's a bad hack, as it uses a private `_dl_get_tls_static_info` symbol.

Thus a very known problem for `dlopen()` shared objects.

According to TLS specification using dynamic TLS model would be best as it would defer initialization. Maybe we should attempt to change TLS model in GEANT10.

**Comment by davidlt** [comment] 2013-11-22 20:24
TLS size reported from `edmWriteConfigs` is **3760**.

**Comment by davidlt** [comment] 2013-11-24 16:09
I believe my speculations/observations might be confirmed by glibc developer. My default `-fPIC` triggers `global-dynamic` TLS model, yet you force it as `initial-exec`. Building an application with a huge static TLS segmented works fine. The whole issue is `dlopen`. Dynamic loaders computes program static TLS storage size right before control is being passed to a program. We should remove `-ftls-model=` flags from GEANT and CMSSW to test it.

```
The problem you are seeing can't be fixed. The error "cannot allocate memory in
static TLS block" is not the same problem as this bug. Your error is that you
have shared objects compiled with static TLS that *require* static TLS space.
The runtime only has a limited amount of static TLS space. It is not possible
(it's an impossibility actually) for the runtime to pre-allocate static TLS
space for dynamically loaded modules because it doesn't know what you will
dlopen. The only fix you have is to find the offending module and request the
author recompile it without static TLS.
```

**Comment by davidlt** [comment] 2013-11-24 18:57
I can confirm, that changing TLS model to correct one in CMSSW and GEANT resolved allocation problem.

**Comment by davidlt** [comment] 2013-11-25 08:17
@civanch here is what I used. Basically you need to keep with defaults for shared objects (fPIC) and use dynamic TLS. There is very little to none documentation on TLS modes, the default for fPIC is dynamic-global. You must use dynamic TLS model to ensure that shared objects is useful, otherwise it very much depends on usage. For example in our case TLS static storage size is too low. Either you set `-ftls-model=` to `*-dynamic` or completely remove the flag and use compiler defaults, which will be based on PIC/non-PIC flags.

In `geant4-toolfile.spec` (still I don't know if we need it):

```
diff --git a/geant4-toolfile.spec b/geant4-toolfile.spec
index f07b766..f086d5f 100644
--- a/geant4-toolfile.spec
+++ b/geant4-toolfile.spec
@@ -36,7 +36,7 @@ cat << \EOF_TOOLFILE >%i/etc/scram.d/geant4core.xml
   <lib name="G4tracking"/>
   <lib name="G4track"/>
   <lib name="G4analysis"/>
-  <flags CXXFLAGS="-DG4MULTITHREADED -ftls-model=initial-exec -pthread"/>
+  <flags CXXFLAGS="-DG4MULTITHREADED -ftls-model=global-dynamic -pthread"/>
   <client>
     <environment name="GEANT4CORE_BASE" default="@TOOL_ROOT@"/>
     <environment name="LIBDIR" default="$GEANT4CORE_BASE/lib"/>
```

GEANT4 10.0 patch:

```
diff --git a/cmake/Modules/Geant4MakeRules_cxx.cmake b/cmake/Modules/Geant4MakeRules_cxx.cmake
index 3fc7030..2e9f5ab 100644
--- a/cmake/Modules/Geant4MakeRules_cxx.cmake
+++ b/cmake/Modules/Geant4MakeRules_cxx.cmake
@@ -158,7 +158,7 @@ if(CMAKE_COMPILER_IS_GNUCXX OR CMAKE_CXX_COMPILER_ID MATCHES "Clang")
   endif()

   # - Multithreading
-  set(GEANT4_MULTITHREADED_CXX_FLAGS "-ftls-model=initial-exec -pthread")
+  set(GEANT4_MULTITHREADED_CXX_FLAGS "-ftls-model=global-dynamic -pthread")
 endif()


diff --git a/config/sys/Darwin-clang.gmk b/config/sys/Darwin-clang.gmk
index ceeba4e..e62efc9 100644
--- a/config/sys/Darwin-clang.gmk
+++ b/config/sys/Darwin-clang.gmk
@@ -10,7 +10,7 @@ ifeq ($(G4SYSTEM),Darwin-clang)
   CXXFLAGS  += -Wwrite-strings -Wpointer-arith -Woverloaded-virtual -pipe
   CXXFLAGS  += -Wno-variadic-macros -Wshadow
   ifdef G4MULTITHREADED
-    CXXFLAGS += -ftls-model=initial-exec -pthread
+    CXXFLAGS += -ftls-model=global-dynamic -pthread
   endif
   ifdef G4OPTIMISE
     CXXFLAGS  += -O2
diff --git a/config/sys/Linux-g++.gmk b/config/sys/Linux-g++.gmk
index 712e25e..9ce60ed 100644
--- a/config/sys/Linux-g++.gmk
+++ b/config/sys/Linux-g++.gmk
@@ -16,7 +16,7 @@ ifeq ($(G4SYSTEM),Linux-g++)
 #
 # CXXFLAGS  += -march=pentium4 -mfpmath=sse
   ifdef G4MULTITHREADED
-    CXXFLAGS += -ftls-model=initial-exec -pthread
+    CXXFLAGS += -ftls-model=global-dynamic -pthread
   endif
   ifdef G4OPTIMISE
     CXXFLAGS  += -O2
```

**Comment by civanch** [comment] 2013-11-25 08:24
This is great that the problem is resolved and we can go ahead. I will contact Geant4 experts about the switch from TLS static to dynamic. Note, that they choose these options in order to reduce CPU penalty introduced with TLS in beginning of MT migration about a year ago.

**Comment by davidlt** [comment] 2013-11-25 08:31
@civanch I understand it, but going with static on shared objects seems particularly a bad idea.

Oneliner description of TLS modes: http://software.intel.com/sites/products/documentation/doclib/iss/2013/compiler/cpp-lin/GUID-6ABFB39C-A478-4974-9A38-170AA13BC623.htm

**Comment by civanch** [comment] 2013-11-25 08:49
Hi David, this was done because of initial measure of 20% CPU penalty. What they are saying now:

 the compiler option "-ftls-model=initial-exe" has been introduced  in order to reduce the performance penalty due by dynamic loading  of thread-local objects within shared libraries.
 Studies made by Xin at that time revealed that without using  such option one has to pay up to 20% slowdown per-thread.

 One thing to notice is that such option is -incompatible- with  "-fpic" (I see that in our GNUmake system scripts we still have it  by mistake - I will correct that; the CMake setup instead is  correct).
 The g++ information explicitly says that the default thread-local  model without -fpic is "initial-exec"; with -fpic the default  becomes "global-dynamic".

 Now, from this thread you forwarded us, it is not clear to me if  -fpic is included in the compiler options for CMSSW. If it is, they  should eventually review it to see if removing it makes a difference.
 One thing is sure, the use of "-fpic" in conjunction with  "-ftls-model=initial-exe" is contradictory!

By the way there is a bug in Geant4 gmake system -fpic is forgotten.

What they proposed to CMS: can we remove -fpic ?

**Comment by davidlt** [comment] 2013-11-25 09:23
fpic/fPIC is almost always used with shared objects, and it will stay. Additional penalties would be added if position independent code is disabled. Everything is compiled with PIC (incl. GEANT4).

If you want to use static TLS storage, when you have to reduce TLS segment size in GEANT4 to **bytes**.

**Comment by civanch** [comment] 2013-11-25 09:28
Hi David, I just submit a small pull request which fix remaining compillation problems. Let us take the new IB build with your receipt and measure CPU. We have recent CPU checks for 7_0_0_pre8.

**Comment by civanch** [comment] 2013-11-27 08:35
It turn out that in regular IB compile options are following: "-ftls-model=initial-exec -pthread -fPIC" and link fail. It is reported that only 1 link is failed but this is not fully true, because plugin libraries are skipped, so teh same problem remain.

I myself cannot do much also with git I do not know how to checkout geant4core from cmsdist.

**Comment by davidlt** [comment] 2013-12-04 11:51
`SimG4Core/PhysicsLists` seems to be missing a header in `CMSSW_7_0_GEANT10_X_2013-12-04-0200`: https://cmssdt.cern.ch/SDT/cgi-bin/buildlogs/slc5_amd64_gcc481/CMSSW_7_0_GEANT10_X_2013-12-04-0200/SimG4Core/PhysicsLists

What exactly would you want to test?

**Comment by civanch** [comment] 2013-12-04 12:42
for SimG4Core/PhysicsLists there is a pull request 1646 which fix compilation. For some reasons it looked as unsigned but it is signed. 

The main problem is that plugins still cannot be linked for any sub-package involving G4

**Comment by davidlt** [comment] 2013-12-04 14:04
I have merged PR CMSSW/1646. Again if you change TLS model from static to global for shared objects it should work. I posted my modifications earlier in the discussion. Tomorrow I could build you another test build on some machine.

**Comment by civanch** [comment] 2013-12-04 14:15
But why the patch of G4 is not propagated to IB? It likely for the time being should be the default.

When I do "scram b" for any new IB I get "-ftls-model=initial-exec -pthread -fPIC" instead of "-ftls-model=global-dynamic -pthread -fPIC".

**Comment by davidlt** [comment] 2013-12-04 14:18
Because I am waiting for your review, go/no-go. If you like, I can apply the changes (TLS static -> dynamic) to the next IB.

**Comment by civanch** [comment] 2013-12-04 14:21
Yes, please, there is no way to go forward without this compromise.

**Comment by davidlt** [comment] 2013-12-04 16:23
Should be in for 0200 IB.

**Comment by civanch** [comment] 2013-12-05 08:54
SIM step become work. CPU penalty versus 7_0_0_pre9 is about 65% - much more than experts predicted.

**Comment by davidlt** [comment] 2013-12-05 09:06
That's the penalty you pay. Again if you want to use a static TLS in dynamic objects you must lower it down to bytes. If you look into _glibc_ implementation, you would find that __thread  / threadlocal is used only on pointers or extremely small structures (int, or a couple of ints).

**Comment by civanch** [comment] 2013-12-05 11:31
Reading more carefully discussion with glibc developer I am confuse: it seems that we do not now the limit on TLS, my interpretation is that he propose to identify it empirically. Geant4 developers agree to work on reduction of TLS and even more possible splitting of the largest library, however, if the target size of the library and of its TLS is unknown it is more difficult to force them to do this promptly. What I observed was the problem not only with the largest library but with other, so the limit is likely below 1000 B. Can it be that the limit in CMSSW is below zero due to some reason?

**Comment by davidlt** [comment] 2013-12-05 11:49
In this thread I already partially showed how static TLS is being computed. It is known how TLS static storage size is computed. It's computed by dynamic loader just before transferring control to the executable. TLS static storage size cannot be affected externally, but glibc is thinking of maybe adding some environment variable for that. TLS static storage size is 1664+ (missing alignment corrections and TCB size). TLS static size in CMSSW is not zero. From my previous look I observed 3760 bytes on static TLS in _edmWriteConfigs_ executable.

As you seen from previous numbers usually the size is less or equal to 100 bytes per library. E.g., I could mark 100 integers for TLS, which would be 400 bytes for TLS storage. That's bad. I could put those 100 integers into a struct and just keep a pointer in TLS and I am down to just 8 bytes of TLS. I don't know how TLS is used in GEANT4, but one way to minimize TLS storage is encapsulating big things into some "context" and just keeping a pointer to it in TLS.

**Comment by civanch** [comment] 2013-12-09 08:45
It turn out that 65% CPU penalty is false, the reason of false report is unexpected slow down of lxbuild170. Checked at lxbuild168 and 170 from 700pre4 to this branch shows that Geant4 10.0 is about 5% faster that Geant4 9.6.

So, this issue is done and can be closed.

**Closed as completed** 2013-12-09 08:59 UTC

**Comment by ktf** [comment] 2013-12-09 09:01
Vladimir, I suggest you use vocms123 to do performance comparison, since 
it is guaranteed to not have IBs running there.

Ciao,
Giulio

**Comment by civanch** [comment] 2013-12-09 09:04
Thanks, I will move to it. Problem with lxbuild170 not so obvious: I have checked with top that it is emptybut it is slowerthese days than a month ago!

**Comment by ktf** [comment] 2013-12-09 09:53
> Thanks, I will move to it. Problem with lxbuild170 not so obvious: I 
> have checked with top that it is emptybut it is slowerthese days than 
> a month ago!

It might be some system update. Will check.
