### ISSUE TITLE
add coral patch and include in CMSSW

### ISSUE THREAD

**Issue by DrDaveD** [cms-sw/cmsdist#306] opened 2014-01-03 18:01 UTC
I have developed a patch for coral that I need included in CMSSW.  I don't see a way to attach a file to a github issue, so find the patch on lxplus at
    ~/public/coral-CORAL_2_3_21-forever-ttl.patch

I have tested this on SLC5 with SCRAM_ARCH=slc5_amd64_gcc481 against release candidate CORAL_2_3_21-cms10 and CMSSW_7_0_0_pre11, and on SLC6 with SCRAM_ARCH=slc6_amd64_gcc481 against CORAL_2_3_21-cms9 and CMSSW_7_0_0_pre11.

Depends on https://github.com/cms-sw/cmsdist/issues/305.

Next I will be submitting this patch to coral for inclusion in a new release of theirs, so in future builds this patch will be able to be removed.

**Comment by ktf** [comment] 2014-01-29 08:29
@degano / @nclopezo, can you please do a build with this? Thanks.

**Comment by ghost** [comment] 2014-01-29 15:40
@DrDaveD, meanwhile something probably changed with the new Frontier and I cannot build your patch:

```
/build/degano/ext/CMSSW_7_0_X/20140129_1528/a/tmp/BUILDROOT/afdc3fb51999bc5091e5889fbdf35b85/opt/cmssw/slc5_amd64_gcc481/cms/coral/CORAL_2_3_21-cms12/src/LCG/FrontierAccess/src/Statement.cpp: In member function 'bool coral::FrontierAccess::Statement::execute(const coral::AttributeList&, int)':
/build/degano/ext/CMSSW_7_0_X/20140129_1528/a/tmp/BUILDROOT/afdc3fb51999bc5091e5889fbdf35b85/opt/cmssw/slc5_amd64_gcc481/cms/coral/CORAL_2_3_21-cms12/src/LCG/FrontierAccess/src/Statement.cpp:282:39: error: 'class frontier::Connection' has no member named 'setTimeToLive'
             m_properties.connection().setTimeToLive( timeToLive );
                                       ^
gmake: *** [tmp/slc5_amd64_gcc481/src/LCG/FrontierAccess/src/lcg_FrontierAccess/Statement.o] Error 1
```

Can you please fix it?

**Comment by DrDaveD** [comment] 2014-01-29 17:18
Sorry, it's ~dwd.  I guess you found that since you got further and had a problem building.  Please point me to the whole log including hopefully the part that applies the patch.  Or if the build files still exist under /build/degano and I can look at those, just tell me the name of the machine.

**Comment by DrDaveD** [comment] 2014-01-29 18:09
@degano  maybe it will be enough if you can just point me to the coral.spec you used

**Comment by ghost** [comment] 2014-01-30 08:35
It actually exists on lxbuild166. Let me know if you find it.

**Comment by ktf** [comment] 2014-01-30 08:49
Path? ;-)

**Comment by ghost** [comment] 2014-01-30 08:52
It is the only ext build I have there, so /build/degano/ext/CMSSW_7_0_X/...

**Comment by DrDaveD** [comment] 2014-01-30 16:24
I see that somehow things are arranged so that the "LCG" directory is called "src" during the build.  So I changed all the LCG's in my patch to src.  It is updated at
~dwd/public/coral-CORAL_2_3_21-forever-ttl.patch
Try that.  Also I noticed that you already had a patchsrc8 in coral.spec in a %if %isarmv7.  I assume that needs to change to patchsrc9 to build on armv7.

**Comment by ghost** [comment] 2014-01-31 09:13
That was not the problem: I found a workaround for that myself.
The problem is at compile time after the patch has been applied.
Thank you for the arm thing, I will fix that.
Can you please check if you can compile the code with your patch on the current version of CMSDIST?

**Comment by DrDaveD** [comment] 2014-01-31 12:35
Are you sure?  I saw in the screenlog.0 that the patch wasn't being applied.  Maybe the log includes multiple attempts?

**Comment by ghost** [comment] 2014-01-31 14:16
Yes, I am sure. The screenlog you found does not refer to the problem I am addressing, but rather to another try.

The problem I am referring to happens at compile time, as you can see in the comment I posted 2 days ago.

Anyway, in the same directory:

```
/build/degano/ext/CMSSW_7_0_X/20140129_1528
```

You will now find again the correct screenlog and also the build log that you can find here:

```
/build/degano/ext/CMSSW_7_0_X/20140129_1528/a/BUILD/slc5_amd64_gcc481/cms/coral/CORAL_2_3_21-cms12/log
```

**Comment by smuzaffar** [comment] 2014-01-31 14:39
@degano , I think you need frontier_client  2.8.9 to go with this patch. From log files , I see your build is still using 2.8.8.

**Comment by DrDaveD** [comment] 2014-01-31 14:40
Ah!  You must not be using frontier_client 2.8.9 or later.  That was just updated to 2.8.10 yesterday, in the 7_1_X build.  I think you should be only applying this patch to 7_1_X now, not 7_0_X.  The plan was to try the frontier client and this patch in 7_1_X first and then backport to 7_0_X.  

I'm sorry I didn't notice this yesterday.  I was only able to give it a little attention because of other urgent fires I was fighting.

**Comment by ktf** [comment] 2014-01-31 14:46
> @degano , I think you need frontier_client  2.8.9 to go with this 
> patch. From log files , I see your build is still using 2.8.8.

2.8.9 is broken. You need 2.8.10. We should already have 2.8.10 in 71X, 
no?

**Comment by ghost** [comment] 2014-01-31 15:24
Yes, sorry I used the wrong release.
Tested and submitted a new pull request here:
#381.

**Comment by ktf** [comment] 2014-01-31 15:31
Will be in next IB.

**Closed as completed by ktf** 2014-01-31 15:31 UTC
