### ISSUE TITLE
Herwig 7 migration to python3

### ISSUE THREAD

**Issue by fabiocos** [cms-sw/cmsdist#5324] opened 2019-11-03 06:52 UTC
Looking at the failures in the PY3 IB I see that test workflow 511.0 (Herwig7 + external ME) fails due to a trivial issue in an internal python script:

```
&gt;&gt;&gt; Compiling MadGraph amplitudes. This may take some time -- please be patient.
&gt;&gt;&gt; In case of problems see ./Herwig-scratch/Build/MadGraphAmplitudes/MG.log for details.

  File "/cvmfs/cms-ib.cern.ch/nweek-02600/slc7_amd64_gcc820/external/herwigpp/7.1.4-fdffeh2/bin/mg2herwig", line 63
    if it.replace("-","").isdigit():
                                   ^
TabError: inconsistent use of tabs and spaces in indentation
Error: Failed to initialize amplitude 'MadGraph'
```

happening in https://phab.hepforge.org/source/herwighg/browse/herwig-7-1/MatrixElement/Matchbox/External/MadGraph/mg2herwig.py.in$63

A closer inspection shows that there are other issues (for instance print statement syntax). There are not so many python scripts in this generator:

```
07:50 cmsdev25 561> find ./Herwig-7.1.4 -name "*.py" -print
./Herwig-7.1.4/Models/Feynrules/python/ufo2peg/particles.py
./Herwig-7.1.4/Models/Feynrules/python/ufo2peg/vertices.py
./Herwig-7.1.4/Models/Feynrules/python/ufo2peg/helpers.py
./Herwig-7.1.4/Models/Feynrules/python/ufo2peg/lorentzparser.py
./Herwig-7.1.4/Models/Feynrules/python/ufo2peg/__init__.py
./Herwig-7.1.4/Models/Feynrules/python/ufo2peg/collapse_vertices.py
./Herwig-7.1.4/Models/Feynrules/python/ufo2peg/write_paramcard.py
./Herwig-7.1.4/Models/Feynrules/python/ufo2peg/converter.py
./Herwig-7.1.4/Models/Feynrules/python/ufo2peg/check_lorentz.py
./Herwig-7.1.4/Models/Feynrules/exampleInputs/particles.py
./Herwig-7.1.4/Models/Feynrules/exampleInputs/couplings.py
./Herwig-7.1.4/Models/Feynrules/exampleInputs/vertices.py
./Herwig-7.1.4/Models/Feynrules/exampleInputs/write_param_card.py
./Herwig-7.1.4/Models/Feynrules/exampleInputs/lorentz.py
./Herwig-7.1.4/Models/Feynrules/exampleInputs/parameters.py
./Herwig-7.1.4/Models/Feynrules/exampleInputs/__init__.py
./Herwig-7.1.4/Models/Feynrules/exampleInputs/function_library.py
./Herwig-7.1.4/Models/Feynrules/exampleInputs/object_library.py
./Herwig-7.1.4/MatrixElement/Matchbox/External/MadGraph/mg2herwig.py
./Herwig-7.1.4/MatrixElement/Matchbox/External/GoSam/gosam2herwig.py
./Herwig-7.1.4/Sampling/herwig-mergegrids.py
./Herwig-7.1.4/Tests/python/histogram.py
./Herwig-7.1.4/Tests/python/compare.py
./Herwig-7.1.4/Tests/python/make_input_files.py
./Herwig-7.1.4/Tests/python/main.py
```

but they should be made python3 compatible.

@qliphy @agrohsje @alberto-sanchez was this already discussed with the authors? Is there already a plan for this?

**Comment by fabiocos** [comment] 2019-11-03 06:52
assign generator

**Comment by fabiocos** [comment] 2019-11-03 06:53
assign generators

**Comment by qliphy** [comment] 2019-11-03 09:26
adding @Andrej-CMS

**Comment by smuzaffar** [comment] 2019-11-19 15:29
looks like both herwigpp and madgraph5amcatnlo need python3 updates

https://bazaar.launchpad.net/~madteam/mg5amcnlo/series2.0/view/head:/bin/mg5_aMC#L23

**Comment by agrohsje** [comment] 2019-11-19 15:33
https://bazaar.launchpad.net/~madteam/mg5amcnlo/series2.0/view/head:/bin/mg5_aMC#L24 :
MadGraph5_aMC@NLO works only with python 2.6 or later (but not python 3.X)
Python 3 is only in preparation but not yet validated from the authors.

**Comment by Andrej-CMS** [comment] 2019-11-20 12:58
Dear @all ,
Please find the statement of the authors below:

 Dear Andrej,

  So we've started looking at it. Most of our python is either in the build, i.e. our bootstrap script for all the dependencies which I guess you're not using, interfacing to things like Madgraph, and our interface to UFO. The build stuff now works with both python 2 and python3. Unfortunately Madgraph doesn't yet so we are waiting on that for the interfaces. I plan to look at the ufo stuff once we get the release out of the way.

  At the moment though I'm hoping we can support both 2 and 3 for a reasonable period once we have a python3 version of madgraph

Best Wishes

Peter

**Comment by davidlange6** [comment] 2019-11-20 13:08
Do we have a plan from madgraph?
I find this...
https://blueprints.launchpad.net/mg5amcnlo/+spec/pythonversion
But not much else

On Nov 20, 2019, at 1:58 PM, Andrej-CMS <notifications@github.com> wrote:


Dear @ALL<https://github.com/ALL> ,
Please find the statement of the authors below:

Dear Andrej,

So we've started looking at it. Most of our python is either in the build, i.e. our bootstrap script for all the dependencies which I guess you're not using, interfacing to things like Madgraph, and our interface to UFO. The build stuff now works with both python 2 and python3. Unfortunately Madgraph doesn't yet so we are waiting on that for the interfaces. I plan to look at the ufo stuff once we get the release out of the way.

At the moment though I'm hoping we can support both 2 and 3 for a reasonable period once we have a python3 version of madgraph

Best Wishes

Peter

**Comment by qliphy** [comment] 2019-11-20 13:19
According to the authors from 28th June:

"Just to keep you updated on the progress here.
1) ALOHA is now fully working with python2/3 and is quite well validated.
2) LO matrix-element (in standalone) are also working with python2/3 and all test seems good.
3) I have successfully run LO event generation (and gridpack generation) with python3 but this is still preliminary so far.
4) I have not yet started to run NLO generation with python3
5) Our test suite is now compatible with python 2/3. But many tests are crashing with python3 (more than 250 unittests are crashing but more than 300 reports correct behaviour)
So I'm now going to look at those 250 tests those related to LO feature and fix them before moving to the  NLO part of the code.
Cheers,
Olivier"

**Comment by qliphy** [comment] 2019-11-20 23:56
What we got from the author yesterday:

"The current status is that the low_mem_multicore option will not be passed to python3 ( they are some very weird pickle issue that I can not fix for python 3). 
For the rest it should be close to working (but you might face some other functionality not working with python3) Now for the when/what version number we will support python3, I can not commit for the moment. 
Cheers, Olivier"

**Comment by mrodozov** [comment] 2021-03-21 20:20
Herwig is now py3 compatible, the failure in 511.0 is from madgraph. Should we rename the issue or open a new one ?

**Comment by qliphy** [comment] 2021-03-22 00:25
@mrodozov   511.0 is  MadGraph showered with Herwig7, and the [failure](
https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc900/CMSSW_11_3_PY3_X_2021-03-19-2300/pyRelValMatrixLogs/run/511.0_QCD_Pt-30_13TeV_aMCatNLO_herwig7+QCD_Pt-30_13TeV_aMCatNLO_herwig7+HARVESTGEN/step1_QCD_Pt-30_13TeV_aMCatNLO_herwig7+QCD_Pt-30_13TeV_aMCatNLO_herwig7+HARVESTGEN.log#/122-122) is still from Herwig7:

Current Modules:
Module: Herwig7GeneratorFilter:generator (crashed)
Module: none
Module: none
Module: none
A fatal system signal has occurred: segmentation violation

@cms-sw/generators-l2 @Dominic-Stafford   Would you please have a look and update us the status of py3 compatibility of herwig7?

**Comment by smuzaffar** [comment] 2021-03-22 10:39
I see that there is also error messages like [a] [here](
https://cmssdt.cern.ch/SDT/cgi-bin/logreader/slc7_amd64_gcc900/CMSSW_11_3_PY3_X_2021-03-19-2300/pyRelValMatrixLogs/run/511.0_QCD_Pt-30_13TeV_aMCatNLO_herwig7+QCD_Pt-30_13TeV_aMCatNLO_herwig7+HARVESTGEN/step1_QCD_Pt-30_13TeV_aMCatNLO_herwig7+QCD_Pt-30_13TeV_aMCatNLO_herwig7+HARVESTGEN.log#/122-122) . Could this be the actual cause of failure

[a]
```
>>> Compiling MadGraph amplitudes. This may take some time -- please be patient.
>>> In case of problems see ./Herwig-cache/Build/MadGraphAmplitudes/MG.log for details.

*** MadGraph build failed, check logfile for details ***Error: Failed to initialize amplitude 'MadGraph'
%MSG-s ModulesSynchingOnLumis:  AfterModConstruction 20-Mar-2021 04:26:12 CET  pre-events
The following modules require synchronizing on LuminosityBlock boundaries:
  Herwig7GeneratorFilter generator
%MSG
determining subprocesses for p p j j 
building matrix elements.
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
*/Herwig/Vertices/HGGVertex has inconsistent number of external particles and coupling order = 3 for a perturbative interaction. Either it's an effective vertex or something is wrong.
**************************************************
created 176 subprocesses.
---------------------------------------------------
preparing Born matrix elements.
Initializing external amplitudes.

>>> Compiling MadGraph amplitudes. This may take some time -- please be patient.
>>> In case of problems see ./Herwig-cache/Build/MadGraphAmplitudes/MG.log for details.

*** MadGraph build failed, check logfile for details ***Error: Failed to initialize amplitude 'MadGraph'
Error: The object '/Herwig/EventHandlers/Luminosity' was not created as another object with that name already exists.
Error: The object '/Herwig/Analysis/HepMC' was not created as another object with that name already exists.
```

**Comment by mrodozov** [comment] 2021-03-22 10:49
I think when I was trying to make this work this log file 
./Herwig-cache/Build/MadGraphAmplitudes/MG.log was clearly showing it was a python problem (over and over py3 incopats one after another)
I see the new versions of madgraph are py3 compatible, starting 2.7.3 but it says py3 only(!) compatible
I'll check that log again and try the 2.7.3 version, also 
@Andrej-CMS do you think we can maybe switch to 2.7.3 ?

**Comment by mrodozov** [comment] 2021-03-22 10:52
> A fatal system signal has occurred: segmentation violation

ah well, ok then maybe it's still not compatible yet :/

**Comment by smuzaffar** [comment] 2021-03-22 10:53
yes initially the error was with py3 ( see https://github.com/cms-sw/cmsdist/issues/5324#issue-516789188  ) , looks like that issue is solved but now we have the next one

**Comment by agrohsje** [comment] 2021-03-22 11:06
@mrodozov:  @Dominic-Stafford  and @theofil (Kostas)  took over from  @Andrej-CMS . 
In central production we use 2.6.5 but I am fine with upgrading to 2.7.3 in workflow 511. Maybe Dominic and Kostas can further check.

**Comment by Dominic-Stafford** [comment] 2021-03-22 12:04
Hi All. Sorry for the delay with this- since this is a Matchbox process, I think the issue is the version of Madgraph in cmsdist, rather than the one in gen productions used for producing Madgraph gridpacks. The Madgraph version in cmsdist seems to still be 2.6.0: https://github.com/cms-sw/cmsdist/blob/IB/CMSSW_11_3_X/py3/madgraph5amcatnlo.spec. @agrohsje and @GurpreetSinghChahal do you know if this version of Madgraph is used by anything other than Herwig (I don't know if it's used in Sherpa gridpacks or something)? If not I'll try upgrading to Madgraph 2.7.3 on the CMSSW PY3 branch, and check this fixes the issue.

**Comment by agrohsje** [comment] 2021-03-22 13:42
Thanks Dominic. It should be fully disentangled from the rest. So no objection to upgrade!

**Closed as completed** 2021-03-24 10:42 UTC
Labels: generators-pending, pending-signatures
