### ISSUE TITLE
igprof -pp loses track of the main thread: how to recover?

### ISSUE THREAD

**Issue by slava77** [cms-sw/cmsdist#3516] opened 2017-10-21 13:55 UTC
[I'm not sure if there is a github repo for igprof and the problem may also be CMS software stack related]

The latest example is in connection with https://github.com/cms-sw/cmssw/pull/19893
using CMSSW_9_4_X_2017-10-19-2300+PR19893
run e.g. a miniAOD part of 10224 (wf 136.7611 will likely have the same problem) in one thread setup.

The igprof apparently  loses track of the main thread at some point and the profiler report is incomplete.
As an example https://slava77sk.web.cern.ch/slava77sk/reco/cgi-bin/igprof-navigator/CMSSW_9_4_X_2017-10-19-2300-sign954.pat-from-aod.10224.IgProf.299.pp
is a dump after 299 events (triggered by the IgProfService) but it has nothing about calls to the event processing.
Running with ```igprof -pp -z  -d -t cmsRun cmsRun step3_PAT.py ``` (debug enabled) shows a bit of useful information [".. text" are my notes], as can be seen in the snippet below

```
.. start: 
*** IgProf(14375, 1508495519.823): profiler activated in cmsRun, main thread id 0x7f9348af9c20
.. ... 
*** IgProf(14375, 1508495531.033): pthread_sigmask(): prevented profiling signal 27 from being blocked in thread 0x7f9348af9c20 [handler 0x7f934ab04d10, interval 5999 us]
*** IgProf(14375, 1508495531.033): pthread_sigmask(): prevented profiling signal 27 from being blocked in thread 0x7f9348af9c20 [handler 0x7f934ab04d10, interval 5999 us]
*** IgProf(14375, 1508495531.034): pthread_sigmask(): prevented profiling signal 27 from being blocked in thread 0x7f9348af9c20 [handler 0x7f934ab04d10, interval 5999 us]
*** IgProf(14375, 1508495531.034): pthread_sigmask(): prevented profiling signal 27 from being blocked in thread 0x7f9348af9c20 [handler 0x7f934ab04d10, interval 5999 us]
*** IgProf(14375, 1508495531.034): captured thread id 0x7f9335c3f700 for profiling (0x7f9348e61c20(0x7f9336b38050))
.. there are no more messages about 0x7f9335c3f700
*** IgProf(14375, 1508495531.034): pthread_sigmask(): prevented profiling signal 27 from being blocked in thread 0x7f9348af9c20 [handler 0x7f934ab04d10, interval 5999 us]
*** IgProf(14375, 1508495531.034): pthread_sigmask(): prevented profiling signal 27 from being blocked in thread 0x7f9348af9c20 [handler 0x7f934ab04d10, interval 5999 us]
20-Oct-2017 12:32:14 CEST  Initiating request to open file file:aodsim.root
.. then at the very end:
*** IgProf(14375, 1508495827.566): exit(0) called in thread 0x7f9348af9c20
*** IgProf(14375, 1508495829.546): final exit in thread 0x7f9348af9c20, saving profile data
*** IgProf(14375, 1508495829.546): dumping state to |gzip -c>pp.gz
*** IgProf(14375, 1508495830.811): trace perf: ntraces=5789 depth=[av 53.4, rms 41.4] ticks=[av 72284.9, rms 216244.1] ticks-per-depth=[av 1879.2, rms 7641.1]
*** IgProf(14375, 1508495830.811): igprof quitting
*** IgProf(14375, 1508495830.811): _exit(0) called in thread 0x7f9348af9c20
```

Is it possible to still get the profiles by activating the profiler later, in this case after the "makeModule" calls are done?

**Comment by smuzaffar** [comment] 2017-10-22 11:37
@slava77 , igprof repo is https://github.com/igprof/igprof  (not sure if it is still maintained)

**Comment by slava77** [comment] 2017-10-22 19:00
@ktf 
does the issue look familiar?

Somewhat related: I tried to add ```-pd ```  to the options (```igprof -pp -pd -z  -d -t cmsRun cmsRun step3_PAT.py```) and run with a IgProfService enabled,
hoping that the dumps will actually trigger collection, but in this case the IgProf files come out essentially empty, with a single line ```P=(HEX ID=44d N=(cmsRun) T=0.005999)```

**Comment by ktf** [comment] 2017-10-23 08:57
@slava77 the issue is actually in libunwind, IIRC. Are you sure you are running with the latest igprof and libunwind?

**Comment by davidlange6** [comment] 2017-10-23 09:01
looks like there is a recent libunwind version that we should try out. (1.2.1)

**Comment by davidlange6** [comment] 2017-10-23 09:36
correction - we have 1.2.1... i guess we could try the development branch?

**Comment by mrodozov** [comment] 2017-10-26 10:42
@slava77 could you try it now with some of the devel ib's, we've updated the version of libunwind there and it should be available in the latest ib's (see https://github.com/cms-sw/cmsdist/pull/3526)

**Comment by slava77** [comment] 2017-10-26 11:33
On 10/26/17 12:42 PM, mrodozov wrote:
> @slava77 <https://github.com/slava77> could you try it now with some of
> the devel ib's, we've updated the version of libunwind there and it
> should be available in the latest ib's (see #3526
> <https://github.com/cms-sw/cmsdist/pull/3526>)

Did you really mean _DEVEL_ IB or the regular ones?
I see that #3526 was merged to the regular cms-sw:IB/CMSSW_9_4_X/gcc630next

I'll try with the regular one after 26-1100 shows up.
It looks like #3526 didn't make it to 25-2300

**Comment by smuzaffar** [comment] 2017-10-26 12:19
IB/CMSSW_9_4_X/gcc630next branch is used for DEVEL IBs, so yes it is currently in DEVEL IBs.

**Comment by slava77** [comment] 2017-12-07 23:42
On 10/26/17 3:42 AM, mrodozov wrote:
> @slava77 <https://github.com/slava77> could you try it now with some of
> the devel ib's, we've updated the version of libunwind there and it
> should be available in the latest ib's (see #3526
> <https://github.com/cms-sw/cmsdist/pull/3526>)

I have finally tested a similar setup with tensorflow running from CMSSW
PR19893
in CMSSW_10_0_X_2017-12-07-1100

the igprof now works
https://slava77sk.web.cern.ch/slava77sk/reco/cgi-bin/igprof-navigator/CMSSW_10_0_X_2017-12-07-1100-sign954.pat-from-aod.10224.100.pp
nice

**Comment by mrodozov** [comment] 2018-02-23 16:52
Can we close the issue then @slava77  ?

**Closed as completed** 2018-02-23 16:58 UTC
Labels: pending-assignment

**Comment by slava77** [comment] 2018-02-23 17:02
sure
I see that it is closed already.
